# Microservice deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kclients
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kclients
  template:
    metadata:
      labels:
        app: kclients
    spec:
      containers:
        - name: app
          image: avecontainerv1.azurecr.io/backend/clients-service
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_URL
              value: postgres:ave123@postgres-db-lb:5432/ave-database-auth-v1
          imagePullPolicy: Always

---
# MicroserviceService
apiVersion: v1
kind: Service
metadata:
  name: kclients-service
spec:
  selector:
    app: kclients
  ports:
    - port: 8080
      targetPort: 8080
---
# MicroserviceIngress
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: kclients-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
          - path: /api/client
            backend:
              serviceName: kclients-service
              servicePort: 8080
          - path: /v3/api-docs/
            backend:
              serviceName: kclients-service
              servicePort: 8080
