apiVersion: v1
kind: Service
metadata:
    name: avecontainerv1azurecriobackendclientsservice
spec:
    type: LoadBalancer
    ports:
    - port: 8080 
    selector:
        app: avecontainerv1azurecriobackendclientsservice